#!/usr/bin/python3
import py_compile
import os

# Get the Python file name from the environment variable
py_file = os.environ.get('PYFILE')

# Check if the environment variable is set
if py_file:
    # Compile the Python file
    output_dir = os.path.dirname(py_file)
    output_file = os.path.splitext(py_file)[0] + '.pyc'
    py_compile.compile(py_file, cfile=output_file, doraise=True)

    print(f"Compiling {py_file} ...")
    print(f"Created {output_file}")
else:
    print("Environment variable $PYFILE is not set.")

